# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcl < Formula
  desc "My CLI for AWS"
  homepage "https://github.com/masuldev/mcl"
  version "1.2.1"

  on_macos do
    on_intel do
      url "https://github.com/masuldev/mcl/releases/download/v1.2.1/mcl_1.2.1_darwin_amd64.tar.gz"
      sha256 "ea4ea59b6b23663ff0900fb057531c03ae8f884a51473ac3ba295ee3202dae40"

      def install
        bin.install "mcl"
      end
    end
    on_arm do
      url "https://github.com/masuldev/mcl/releases/download/v1.2.1/mcl_1.2.1_darwin_arm64.tar.gz"
      sha256 "2d52187e4f18767ac0b30dd3428f7d89fcd24fe6f35b3c06c62a8e695f1792d9"

      def install
        bin.install "mcl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/masuldev/mcl/releases/download/v1.2.1/mcl_1.2.1_linux_amd64.tar.gz"
        sha256 "327cec88b746cfff2161072a1d7196cd010b94c2b4232b06d2d5c286f1a078fd"

        def install
          bin.install "mcl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/masuldev/mcl/releases/download/v1.2.1/mcl_1.2.1_linux_arm64.tar.gz"
        sha256 "aa5eec3347e4bb193a6f753eceab7fce998a3fed6f567773175a4f3097df4cdc"

        def install
          bin.install "mcl"
        end
      end
    end
  end

  test do
    system "#{bin}/mcl", "--version"
  end
end
