# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcl < Formula
  desc "mcl is interactive CLI"
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masuldev/mcl/releases/download/v0.0.3/mcl_0.0.3_Darwin_arm64.tar.gz"
      sha256 "81413894f383a390b780ca8cef8f0fab5fd445b1bca215cee65630c2f016d05b"

      def install
        bin.install "mcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masuldev/mcl/releases/download/v0.0.3/mcl_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "aff0f56d09963c01d968f2214e351c677d7bde39526ef49f23aa961a6ffc1e5a"

      def install
        bin.install "mcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masuldev/mcl/releases/download/v0.0.3/mcl_0.0.3_Linux_arm64.tar.gz"
      sha256 "fa0994ae64ff50c99bbcbfdd7c2478549c0171e42b65dfcc09b9b5b275519176"

      def install
        bin.install "mcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masuldev/mcl/releases/download/v0.0.3/mcl_0.0.3_Linux_x86_64.tar.gz"
      sha256 "eac7abad1b7619afb86108b66f9a280a15c7c013d5ef74ad62528c046f2a4f10"

      def install
        bin.install "mcl"
      end
    end
  end
end
